let now = new Date()
console.log(now)
console.log(now.getDate())
console.log(now.getFullYear())
console.log(now.getMonth())
console.log(now.toLocaleDateString('pt-BR'))
console.log(now.toLocaleTimeString('pt-BR'))